export const THIRD_PARTY_LICENSES = [
  {
    name: "React",
    version: "19.0.0",
    license: "MIT",
    copyright: "Copyright (c) Meta Platforms, Inc. and affiliates.",
    url: "https://react.dev",
  },
  {
    name: "React DOM",
    version: "19.0.0",
    license: "MIT",
    copyright: "Copyright (c) Meta Platforms, Inc. and affiliates.",
    url: "https://react.dev",
  },
  {
    name: "Electron",
    version: "43.1.0",
    license: "MIT",
    copyright: "Copyright (c) Electron contributors\nCopyright (c) 2013-2020 GitHub Inc.",
    url: "https://www.electronjs.org",
  },
  {
    name: "Vite",
    version: "6.4.3",
    license: "MIT",
    copyright: "Copyright (c) 2019-present VoidZero Inc. and Vite contributors",
    url: "https://vitejs.dev",
  },
  {
    name: "Material Symbols",
    version: "0.45.6",
    license: "Apache-2.0",
    copyright: "Copyright (c) Google",
    url: "https://fonts.google.com/icons",
  },
  {
    name: "esbuild",
    version: "0.28.1",
    license: "MIT",
    copyright: "Copyright (c) Evan Wallace",
    url: "https://github.com/evanw/esbuild",
  },
  {
    name: "FastAPI",
    version: "0.115.0",
    license: "MIT",
    copyright: "Copyright (c) Sebastián Ramírez",
    url: "https://fastapi.tiangolo.com",
  },
  {
    name: "Uvicorn",
    version: "0.34.0",
    license: "BSD-3-Clause",
    copyright: "Copyright (c) 2019 Tom Christie",
    url: "https://www.uvicorn.org",
  },
  {
    name: "SQLAlchemy",
    version: "2.0.0",
    license: "MIT",
    copyright: "Copyright (c) SQLAlchemy team",
    url: "https://www.sqlalchemy.org",
  },
  {
    name: "Pydantic",
    version: "2.10.0",
    license: "MIT",
    copyright: "Copyright (c) Pydantic Team",
    url: "https://docs.pydantic.dev",
  },
  {
    name: "HTTPX",
    version: "0.27.0",
    license: "BSD-3-Clause",
    copyright: "Copyright (c) Encode",
    url: "https://www.python-httpx.org",
  },
  {
    name: "psutil",
    version: "5.9.0",
    license: "BSD-3-Clause",
    copyright: "Copyright (c) 2009, Giampaolo Rodola",
    url: "https://psutil.readthedocs.io",
  },
  {
    name: "gradio_client",
    version: "1.0.0",
    license: "Apache-2.0",
    copyright: "Copyright (c) Gradio Team",
    url: "https://www.gradio.app",
  },
  {
    name: "Pillow",
    version: "10.0.0",
    license: "MIT-CMU",
    copyright: "Copyright (c) 1997-2011 Python Imaging Library (PIL) developers\nCopyright (c) 2011-2024 Pillow developers",
    url: "https://python-pillow.org",
  },
  {
    name: "MCP",
    version: "1.0.0",
    license: "MIT",
    copyright: "Copyright (c) Anthropic PBC",
    url: "https://github.com/modelcontextprotocol/python-sdk",
  },
  {
    name: "send2trash",
    version: "1.8.3",
    license: "BSD-3-Clause",
    copyright: "Copyright (c) 2011-2024 Send2Trash contributors",
    url: "https://github.com/arsenetar/send2trash",
  },
] as const;

export type LicenseEntry = typeof THIRD_PARTY_LICENSES[number];